name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ðŸ›Žï¸
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: Update Theme ðŸ”§ 
        run: git submodule update --init --recursive

      - name: Setup Hugo ðŸ”§
        run: | 
          sudo apt update
          wget ${{ secrets.HUGO_RELEASE }} -O hugo.deb
          sudo dpkg -i hugo.deb
          sudo apt install -f
      - name: Testing Hugo ðŸ”§
        run: 'command -v hugo >/dev/null 2>&1 || { echo >&2 "Where is Hugo? Aborting."; exit 1; }'

      - name: Build blog ðŸ”§
        run: hugo -D --minify

      - name: Deploy ðŸš€
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          BRANCH: gh-pages
          FOLDER: public
          CLEAN: true 